### ISSUE TITLE
Build interrupted silently

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2532]
This issue was originally created at: 2009-12-12 04:07:52.
This issue was reported by: `v1s0r`.
v1s0r said at 2009-12-12 04:07:52
>Windows XP, Mingw rumtime 3.17, gcc 4.4
> 
>There is NOT problem on Lunux (Kubuntu 9.10)
> 
>Try to build this SConstruct:
```python
import os.path
 
env = Environment(tools=["mingw"]) # or without tools
 
env["BINPATH"] = "foo"
env["PROGNAME"] = "bar"
 
env.Program(os.path.join("#$BINPATH", "$PROGNAME"), ["spam.cpp"])
```
>After 3 hours I found a problem:
>SCons.Subst.py, line 406
```python
    try:
        def sub_match(match, conv=self.conv, expand=self.expand, lvars=lvars):
            return conv(expand(match.group(1), lvars))
        result = _dollar_exps.sub(sub_match, args)
    except TypeError:
        ...
    except: # it's my code
        import traceback, sys
        traceback.print_exc(file=sys.stdout)
```
>Output:
```
Traceback (most recent call last):
  File "c:\python\Lib\site-packages\scons-1.2.0\SCons\Subst.py", line 494, in substitute
    result = _dollar_exps.sub(sub_match, args)
  File "c:\python\Lib\site-packages\scons-1.2.0\SCons\Subst.py", line 493, in sub_match
    return conv(expand(match.group(1), lvars))
  File "c:\python\Lib\site-packages\scons-1.2.0\SCons\Subst.py", line 432, in expand
    raise_exception(e, self.target, s)
  File "c:\python\Lib\site-packages\scons-1.2.0\SCons\Subst.py", line 59, in raise_exception
    raise SCons.Errors.BuildError, (target[0], msg)
BuildError: AttributeError `'str' object has no attribute 'exe'' trying to evaluate `$PROGNAME.exe'
```
gregnoel said at 2010-01-18 15:41:36
>Bug party triage.  Steven sez, "I just figured out a pretty simple fix," so give it to him.  Do it the first thing after the 2.0 conversion is out.

garyo said at 2012-09-01 10:01:49
>Bumping all old issues targeted for past releases to 2.x.

**Comment by mwichmann** [comment]
Not much information here.  A key line is different in the current codebase... in `sub_match`, 
```python
        return self.conv(self.expand(match.group(1), lvars))
```
Perhaps whatever this was is no longer an issue?
