### ISSUE TITLE
CheckTypeSize fails when VS2010 /TP flag is used

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2808]
This issue was originally created at: 2012-01-06 16:06:09.
This issue was reported by: `ahelwer`.
ahelwer said at 2012-01-06 16:06:09
>The `/TP` flag forces the VS2010 compiler to use its C++ compiler regardless of file type. If this flag is set when the configure function `CheckTypeSize` is called, the call will always fail and return 0. Setting `language='C++'` as a function parameter does not fix this issue.
> 
>OS: Windows 7 Professional 64-bit
>Compiler: Visual Studio 2010
> 
>SConstruct which reproduces this issue:
```python
env = Environment()
conf = env.Configure()
print 'size int: %d' %conf.CheckTypeSize('int', language='C++')
print 'size long: %d' %conf.CheckTypeSize('long long')
env = conf.Finish()
env.MergeFlags(['/TP'])
conf = env.Configure()
print 'size int: %d' %conf.CheckTypeSize('int', language='C++')
print 'size long: %d' %conf.CheckTypeSize('long long')
env = conf.Finish()
```

**Comment by mwichmann** [comment]
Do we expect Configure to work properly on MSVC?  Don't think it knows about any special modes from there...

**Comment by bdbaddog** [comment]
> Do we expect Configure to work properly on MSVC? Don't think it knows about any special modes from there...

Yes.
My guess is the generated C code for the checker isn't valid c++?

**Comment by mwichmann** [comment]
Okay, I just ran this experiment, with the same result (post-4.5 git).  The sources generated for the two "int" tests are identical, as are the two "long long" tests.  The `config.log` contains clues, though - since the failure is the same, I'll just paste one of them.
```
scons: Configure: Checking size of int ...
.sconf_temp\conftest_19c49762b3bc750364e6d629f7a2c00a_1.cpp <-
  |
  |#include <stdlib.h>
  |#include <stdio.h>
  |int main(void) {
  |    printf("%d", (int)sizeof(int));
  |    return 0;
  |}
  |
cl /Fo.sconf_temp\conftest_19c49762b3bc750364e6d629f7a2c00a_1.obj /c .sconf_temp\conftest_19c49762b3bc750364e6d629f7a2c00a_1.cpp /TP /nologo
conftest_19c49762b3bc750364e6d629f7a2c00a_1.cpp
scons: Configure: Caught exception while building ".sconf_temp\conftest_19c49762b3bc750364e6d629f7a2c00a_1_5d6332091e2d0210f808f48df7561e62.exe":

Traceback (most recent call last):
  File "C:\Users\mats\Documents\github\scons\scripts\..\SCons\Taskmaster\Job.py", line 219, in start
    task.prepare()
  File "C:\Users\mats\Documents\github\scons\scripts\..\SCons\Taskmaster\__init__.py", line 201, in prepare
    t.prepare()
  File "C:\Users\mats\Documents\github\scons\scripts\..\SCons\Node\FS.py", line 3168, in prepare
    SCons.Node.Node.prepare(self)
  File "C:\Users\mats\Documents\github\scons\scripts\..\SCons\Node\__init__.py", line 739, in prepare
    raise SCons.Errors.StopError(msg % (i, self))
SCons.Errors.StopError: Implicit dependency `C:\TP' not found, needed by target `.sconf_temp\conftest_19c49762b3bc750364e6d629f7a2c00a_1_5d6332091e2d0210f808f48df7561e62.exe'.
scons: Configure: no
```

That makes it pretty clear what's wrong: `MergeFlags` has no idea about msvc compiler switches, and so it just does whatever it wants to with that. In fact, what it does is try to put it in `LIBS` - as documented:

>Any other strings not associated with options are assumed to be the names of libraries and added to the `$LIBS` construction variable. 

If you add the flag directly to `CCFLAGS`, `CheckTypeSize` works as expected.

I'd propose we just close this as invalid usage.

I could add a sterner note that this doesn't work for msvc flags, although `ParseFlags` does sort of say that already:

>Parses one or more strings containing typical command-line flags for GCC-style tool chains

**Comment by bdbaddog** [comment]
Ugh. I guess to properly implement MergeFlags, each compiler/linker would have to provide an implementation to parse and segregate the flags presented.

I think minimally we'd have to add a blurb about MergeFlags() only working with gcc-style tool chains as well.
It's indirectly there through the reference to ParseFlags().

So maybe update MergeFlags manpage entry, and file an enhancement request to add parsing MSVC flags to ParseFlags?
