### ISSUE TITLE
When scons is run from virtualenv without activation with py3.5+ it fails finding SCons.Script

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#3277]
Below works fine if you add `. venv36/bin/activate` before running scons.
So there's an issue setting up reasonable sys.path when not activated.

```
$ virtualenv-3.6 venv36
$ venv36/bin/pip install scons
$ venv36/bin/scons
SCons import failed. Unable to find engine files in:
  venv36/lib/scons-3.0.4
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/scons-3.0.4
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/scons-3.0.4
  venv36/lib/scons
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/scons
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/scons
Traceback (most recent call last):
  File "venv36/bin/scons", line 195, in <module>
    import SCons.Script
ImportError: No module named SCons.Script
```

**Comment by mwichmann** [comment]
Any chance this is related to #3271 ?

**Comment by mwichmann** [comment]
If I try to reproduce this, and do:
```
head -n 1 venv36/bin/scons
```
I get:
```
#! /usr/bin/env python
```
So this is nothing to do with scons virtualenv support, instead it's the problem that scons is not correctly "branded" when pip-installed. I believe this is the issue mentioned in the first paragraph of #2891, and on #scons IRC channel just the other day. 

If I invoke it like this, scons seems to work:
```
venv36/bin/python venv36/bin/scons
```

**Comment by scottj97** [comment]
I just hit this myself when trying SCons for the first time.

Python scripts in `venv/bin/*` should have the shebang line pointing to the specific venv's `bin/python` and not rely on PATH.

**Comment by clemens-tolboom** [comment]
I'm on Mac using **conda** + `brew install scons`

```bash
conda activate

python --version
# Python 3.7.4

scons --version

which scons
# /usr/local/bin/scons
```

running `scons` gives similar error

```bash
(base) Clemenss-MacBook-Pro:godot clemens$ scons platform=osx --jobs=$(sysctl -n hw.logicalcpu)
SCons import failed. Unable to find engine files in:
  /usr/local/lib/scons-3.1.2
  /Users/clemens/lib/miniconda3/lib/scons-3.1.2
  /usr/local/lib/python3.7/site-packages/scons-3.1.2
  /Users/clemens/lib/miniconda3/lib/python3.7/site-packages/scons-3.1.2
  /Users/clemens/lib/miniconda3/lib/scons-3.1.2
  /usr/local/lib/scons
  /Users/clemens/lib/miniconda3/lib/scons
  /usr/local/lib/python3.7/site-packages/scons
  /Users/clemens/lib/miniconda3/lib/python3.7/site-packages/scons
  /Users/clemens/lib/miniconda3/lib/scons
Traceback (most recent call last):
  File "/usr/local/bin/scons", line 195, in <module>
    import SCons.Script
ModuleNotFoundError: No module named 'SCons'
```

### Fix

Installing through conda fixed this

```bash
conda install scons
scons platform=osx --jobs=$(sysctl -n hw.logicalcpu)
# starts compiling the project
```

**Comment by bdbaddog** [comment]
> I'm on Mac using **conda** + `brew install scons`
> 
> ```shell
> conda activate
> 
> python --version
> # Python 3.7.4
> 
> scons --version
> 
> which scons
> # /usr/local/bin/scons
> ```
> 
> running `scons` gives similar error
> 
> ```shell
> (base) Clemenss-MacBook-Pro:godot clemens$ scons platform=osx --jobs=$(sysctl -n hw.logicalcpu)
> SCons import failed. Unable to find engine files in:
>   /usr/local/lib/scons-3.1.2
>   /Users/clemens/lib/miniconda3/lib/scons-3.1.2
>   /usr/local/lib/python3.7/site-packages/scons-3.1.2
>   /Users/clemens/lib/miniconda3/lib/python3.7/site-packages/scons-3.1.2
>   /Users/clemens/lib/miniconda3/lib/scons-3.1.2
>   /usr/local/lib/scons
>   /Users/clemens/lib/miniconda3/lib/scons
>   /usr/local/lib/python3.7/site-packages/scons
>   /Users/clemens/lib/miniconda3/lib/python3.7/site-packages/scons
>   /Users/clemens/lib/miniconda3/lib/scons
> Traceback (most recent call last):
>   File "/usr/local/bin/scons", line 195, in <module>
>     import SCons.Script
> ModuleNotFoundError: No module named 'SCons'
> ```
> 
> ### Fix
> Installing through conda fixed this
> 
> ```shell
> conda install scons
> scons platform=osx --jobs=$(sysctl -n hw.logicalcpu)
> # starts compiling the project
> ```

@clemens-tolboom  - if you're having an issue with conda packaged scons, I'd sugguest reaching out to conda project or whoever manages the scons conda project. I have no idea how they package, or if it's the same mechanism as venv.. 

Also note when 4.0.0 is released (I'm working on the last few issues before we can release 4.0.0 now) we've revamped the packaging and I'd expect this issue to go away.

Can you install a pip package in conda? We have a development(not released yet) wheel available for 4.0.0

**Comment by clemens-tolboom** [comment]
@bdbaddog ehm

> Fix
Installing through conda fixed this

**Comment by bdbaddog** [comment]
> @bdbaddog ehm
> 
> > Fix
> > Installing through conda fixed this

I blame caffeine shortage.. ;)
Anyway should be fixed everywhere in 4.0.0
