### ISSUE TITLE
Configure using TryLink + MD5-Timestamp decider fails sometimes throwing exceptions

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#3283]
With SCons 3.0.2 - 3.0.4 Using a SConscript as follows:

```
env = Environment()
env.Decider('MD5-timestamp')
conf = Configure(env)
conf.TryLink('int main(){return 0;}','.c')
env = conf.Finish()
```

Then run:
```
scons --config=force
scons --config=force
```
Will yield the following in config.log (but not always stop scons execution and sometimes thrown an exception and stop scons)

```
file /private/var/folders/lq/rv6t78m16tl956sgcx0gkg440000gn/T/testcmd.1133.dE20vQ/SConstruct,line 3:
	Configure(confdir = .sconf_temp)
.sconf_temp/conftest_0.c <-
  |int main(){return 0;}
scons: Configure: Caught exception while building ".sconf_temp/conftest_0.o":

Traceback (most recent call last):
  File "/Users/bdbaddog/devel/scons/git/as_scons/src/script/../engine/SCons/Job.py", line 201, in start
    task.execute()
  File "/Users/bdbaddog/devel/scons/git/as_scons/src/script/../engine/SCons/SConf.py", line 367, in execute
    raise e
TypeError: 'NoneType' object is not callable
```

**Comment by bdbaddog** [comment]
Fixed in master.
