### ISSUE TITLE
Substfile can't pass through Windows paths due to use of `re.sub`

### ISSUE THREAD

**Issue by acmorrow** [SCons/scons#3550]
**Describe the bug**
You can't pass a Windows path in a value to be interpolated, because SCons will try to pass it through `re.sub` which rejects certain character sequences.

**Required information**
* Link to SCons Users thread discussing your issue.
Discussed on slack

* Version of SCons
3.1.2

* Version of Python
3.7

* Which python distribution if applicable (python.org, cygwin, anaconda, macports, brew,etc)
brew

* How you installed SCons
brew

* What Platform are you on? (Linux/Windows and which version)
macOS

* How to reproduce your issue?  Please include a small self contained reproducer. Likely a SConstruct should do for most issues.
```
import sys

env = Environment()

env['FOO_PATH'] = r'Z:\mongo\build\install\bin'

foo = env.Substfile(
    target="foo",
    source="foo.in",
    SUBST_DICT={
        "@foo_path@" : "$FOO_PATH",
    }
)

```

Given a `foo.in` that looks like:
```
$ cat foo.in
foo_path: @foo_path@
```

This will fail as follows:
```
scons                                                                                                                                            ✔ 0
scons: Reading SConscript files ...
/Users/acm/.virtualenvs/mongo/bin/python
scons: done reading SConscript files.
scons: Building targets ...
Creating 'foo'
scons: *** [foo] error : bad escape \m at position 2
Traceback (most recent call last):
  File "/Users/acm/.virtualenvs/mongo/lib/python3.7/sre_parse.py", line 1015, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\m'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/scons/3.1.2/libexec/scons-local/SCons/Action.py", line 1209, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
  File "/usr/local/Cellar/scons/3.1.2/libexec/scons-local/SCons/Tool/textfile.py", line 142, in _action
    target_file.write(_do_subst(line, subs))
  File "/usr/local/Cellar/scons/3.1.2/libexec/scons-local/SCons/Tool/textfile.py", line 77, in _do_subst
    contents = re.sub(k, val, contents)
  File "/Users/acm/.virtualenvs/mongo/lib/python3.7/re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/Users/acm/.virtualenvs/mongo/lib/python3.7/re.py", line 309, in _subx
    template = _compile_repl(template, pattern)
  File "/Users/acm/.virtualenvs/mongo/lib/python3.7/re.py", line 300, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "/Users/acm/.virtualenvs/mongo/lib/python3.7/sre_parse.py", line 1018, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \m at position 2
scons: building terminated because of errors.
```

* How you invoke scons (The command line you're using "scons --flags some_arguments")
`scons`

**Comment by bdbaddog** [comment]
Should be fixed by #3551
