### ISSUE TITLE
pip-installed SCons directory has improper case, imports fail

### ISSUE THREAD

**Issue by efahl** [SCons/scons#3736]
Win 10 Pro 64
Python 3.8.3
pip 20.1.1

When SCons 4.0 is installed over SCons 3.1 using pip, the character case of the name of the installation in site-packages is incorrect resulting in all scripts that "import SCons" to fail.  Performing "pip uninstall scons" and re-installing fixes this.
```
Traceback (most recent call last):
  File "c:\program files\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python38\Scripts\scons.exe\__main__.py", line 4, in <module>
    SCons.Script.main()
ModuleNotFoundError: No module named 'SCons'
```
The following trace was done in a cygwin shell, but I ran it in Windows cmd and got the same behavior.  Tested on two different machines (same OS release, Python and pip versions), and got the same behavior on both.

```
$ ll -d t:/Python38/Lib/site-packages/[Ss][Cc]*
drwxr-xr-x 1 efahlgren Domain Users 0 2020-01-30 14:51 t:/Python38/Lib/site-packages/scons/
drwxr-xr-x 1 efahlgren Domain Users 0 2020-01-30 14:51 t:/Python38/Lib/site-packages/scons-3.1.2.dist-info/

$ pip install SCons==4.0.0
Looking in indexes: http://docs.lifemodeler.com/simple
Collecting SCons==4.0.0
  Downloading SCons-4.0.0-py3-none-any.whl (4.0 MB)
Requirement already satisfied: pywin32>=1.0; platform_system == "Windows" in c:\program files\python38\lib\site-packages (from SCons==4.0.0) (228)
Requirement already satisfied: setuptools in c:\program files\python38\lib\site-packages (from SCons==4.0.0) (48.0.0)
Installing collected packages: SCons
  Attempting uninstall: SCons
    Found existing installation: scons 3.1.2
    Uninstalling scons-3.1.2:
      Successfully uninstalled scons-3.1.2
Successfully installed SCons-4.0.0

$ ll -d t:/Python38/Lib/site-packages/[Ss][Cc]*
drwxr-xr-x 1 efahlgren Domain Users 0 2020-07-05 06:59 t:/Python38/Lib/site-packages/scons/
drwxr-xr-x 1 efahlgren Domain Users 0 2020-07-05 06:59 t:/Python38/Lib/site-packages/SCons-4.0.0.dist-info/

$ pip uninstall scons -y
Found existing installation: SCons 4.0.0
Uninstalling SCons-4.0.0:
  Successfully uninstalled SCons-4.0.0

$ pip install scons==4.0.0
Looking in indexes: http://docs.lifemodeler.com/simple
Collecting scons==4.0.0
  Downloading SCons-4.0.0-py3-none-any.whl (4.0 MB)
Requirement already satisfied: pywin32>=1.0; platform_system == "Windows" in c:\program files\python38\lib\site-packages (from scons==4.0.0) (228)
Requirement already satisfied: setuptools in c:\program files\python38\lib\site-packages (from scons==4.0.0) (48.0.0)
Installing collected packages: scons
Successfully installed scons-4.0.0

$ ll -d t:/Python38/Lib/site-packages/[Ss][Cc]*
drwxr-xr-x 1 efahlgren Domain Users 0 2020-07-05 07:00 t:/Python38/Lib/site-packages/SCons/
drwxr-xr-x 1 efahlgren Domain Users 0 2020-07-05 07:00 t:/Python38/Lib/site-packages/SCons-4.0.0.dist-info/
```

**Comment by efahl** [comment]
Per Bill's request, I also tried 'pip install SCons==4.0'  (note upper case package name on command line) and it also fails to update the character case of the new installation.

I played with several pip options, '--exists-action w' (wipe) did nothing.  I then found that re-installing 4.0 over itself seems to fix the name.
```
$ pip install --force scons==4.0 --no-deps
Looking in indexes: http://docs.lifemodeler.com/simple
Collecting scons==4.0
  Downloading SCons-4.0.0-py3-none-any.whl (4.0 MB)
Installing collected packages: scons
  Attempting uninstall: scons
    Found existing installation: scons 3.1.2
    Uninstalling scons-3.1.2:
      Successfully uninstalled scons-3.1.2
Successfully installed scons-4.0.0

$ ll t:/Python38/Lib/site-packages/[Ss][cC]* -d
drwxr-xr-x 1 efahlgren Domain Users 0 2020-07-05 07:24 t:/Python38/Lib/site-packages/scons/
drwxr-xr-x 1 efahlgren Domain Users 0 2020-07-05 07:24 t:/Python38/Lib/site-packages/SCons-4.0.0.dist-info/

$ pip install --force scons==4.0 --no-deps
Looking in indexes: http://docs.lifemodeler.com/simple
Collecting scons==4.0
  Downloading SCons-4.0.0-py3-none-any.whl (4.0 MB)
Installing collected packages: scons
  Attempting uninstall: scons
    Found existing installation: SCons 4.0.0
    Uninstalling SCons-4.0.0:
      Successfully uninstalled SCons-4.0.0
Successfully installed scons-4.0.0

$ ll t:/Python38/Lib/site-packages/[Ss][cC]* -d
drwxr-xr-x 1 efahlgren Domain Users 0 2020-07-05 07:24 t:/Python38/Lib/site-packages/SCons/
drwxr-xr-x 1 efahlgren Domain Users 0 2020-07-05 07:24 t:/Python38/Lib/site-packages/SCons-4.0.0.dist-info/
```

**Comment by bdbaddog** [comment]
I think SCons is actually correct and previous packaging is actually wrong.
Going to mark this as closed.
The proper fix is to uninstall pre-4.0.0 and reinstall.
I'm not sure we can do anything in our installer to force that.

**Comment by efahl** [comment]
Yes, I definitely agree that the new installer is correct and pip is the culprit, and also agree that finding a fix _in the SCons installer_ would be very difficult.  We have a workaround and hopefully this bug report will draw the attention of search engines, so if people have this problem they can find the workaround.

**Comment by bdbaddog** [comment]
There's also a not in the RELEASE.txt doc
https://scons.org/scons-400-is-available.html
