### ISSUE TITLE
importlib_metadata.PackageNotFoundError: No package metadata was found for SCons

### ISSUE THREAD

**Issue by wangyanjiong163** [SCons/scons#3813]
## or join our Discord server : https://discord.gg/bXVpWAy

**Describe the bug**
After installed scons by "sudo python3 setup.py install" and check the version by "scons -v", I got error report like:

Traceback (most recent call last):
  File "/usr/bin/scons", line 33, in <module>
    sys.exit(load_entry_point('SCons==4.0.1', 'console_scripts', 'scons')())
  File "/usr/bin/scons", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/home/mi/.local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 558, in distribution
    return Distribution.from_name(distribution_name)
  File "/home/mi/.local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 215, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for SCons

**Required information**
How to resolved this? 

Thanks.

**Comment by bdbaddog** [comment]
Which distro?
Which distro version?
Where did you download the package?
Can you try with `pip install` instead of `setup.py install`?

**Comment by bdbaddog** [comment]
Also please follow issue filing directions which are in the template you seem to have ignored...

If possible please come to the discord server to discuss your issue.
